### ISSUE TITLE
Feature Request - Responsive Template

### ISSUE THREAD

**Issue by MarkPerryBV** [SoCreate/angular-playground#122]
Love the playground but what it really needs is the ability to host the same component at different screen widths so I can design the component responsively.

Would love to see the same component rendered at sm, md, lg, xl screen widths.

Also the ability to render the component in different languages would also be nice.

And the ability to render a HTML version of the component from the scenario template so other devs can copy and paste.

**Comment by brianmtreese** [comment]
Hey Mark thanks for the feedback! These are all great suggestions that we have encountered as well. We have employed a few different techniques to get us what we need.

**Responsive Option 1**
We actually have an app in which we apply three different html classes on a parent container depending on the width of this container (small, medium and large). Sometimes our components look the same across all three and some times they change. When they need to change we isolate these changes in the individual component styles using :host(.small) { ... }, :host(.medium) { ... }, and :host(.large) { ... }. Then in our sandbox scenarios we just include the component three times over wrapped in these containers. I get that your app probably doesn't have this sort of thing and may not be practical for your situation. But we do have some internal development components we use to make this a little easier so if you're interested in this type of thing I can give you a few more details.

**Responsive Option 2**
We've also used iframes when we actually need to develop with media queries. What we do is sandbox the component as we normally would in a single isolated scenario. Then we create another scenario in which we iframe the previous scenario in as many times as we need providing each individual iframe the width that is needed to trigger the specific break point.

**Language**
Unfortunately we haven't had much experience with this yet but we'll be looking into this more and more over the coming months and may find something to help here as well.

**HTML Preview**
We actually use the playground in our own internal documentation for our dev teams. We do this using iframes and the [embed mode](http://www.angularplayground.it/docs/how-to/embedding-sandboxes). When doing this we encountered the same issue, needing to see the HTML. We found that we needed to manually create this example code in order to make it most useful for our examples. 

So, what we have done is create a "dev" module in which we put anything that is only related to the development of our app but not used in production. In this module we have various helper components, directives, etc. One of these such items is a custom directive that uses a combination of [Marked](https://marked.js.org/#/README.md#README.md) for processing markdown and [Prism](https://prismjs.com/) for syntax highlighting. This directive can then be applied to process the content from an external HTML file to render properly formatted/highlighted code snippets which we include in our sandbox scenarios where needed.

Hope this info helps and these are all things are continually looking to improve.

**Comment by arroyocode** [comment]
@MarkPerryBV, thank you for your use of Playground! As @brianmtreese indicated, the use of the "dev" module satisfies our internal need so I'm afraid this is not something we're planning to build into Playground in the foreseeable future so we're going to close this issue.
