### ISSUE TITLE
PlaygroundModule is not an NgModule

### ISSUE THREAD

**Issue by isaacplmann** [SoCreate/angular-playground#14]
When I run `angular-playground`, the first build always fails with a message "PlaygroundModule is not an NgModule".  If I save any file, webpack rebuilds successfully.

This is a minor annoyance when running `angular-playground` because it automatically triggers a rebuild.  When you run with `-no-serve` and manually run with `ng serve -a playground` you have to know to save a file manually in order to make it build.  This could confuse new users.

**Comment by jschwarty** [comment]
I noticed that and I think this might be an issue in AngularCLI that is
causing this. I am going to investigate it further this afternoon and let
you know!

**Comment by jschwarty** [comment]
Looks like this is due to the fact that the Angular CLI code (probably @ngtools/webpack more specifically) is reflecting on the bootstrap code and the entry module and trying to "reflect" through the TypeScript code. The Playground app code is transpiled before publish, so it is delivered on npm install as JavaScript. We can fix this by delivering the TS files for the `app` folder code of Playground.
