### ISSUE TITLE
ngx-translate integration

### ISSUE THREAD

**Issue by kurpav** [SoCreate/angular-playground#144]
Are there any ways to provide translations to angular-playground module?
I can import that module with config.
```
PlaygroundModule
  .configure({
    selector: 'vd-root',
    overlay: false,
      TranslateModule.forRoot(translateConfig)
    ]
  });
```
Then I need to set default locale somewhere.
Where I can do it?

**Comment by timstoddard** [comment]
Hello @kurpav,

Yes, the ngx-translate module should work with Angular Playground. When using a sandbox, it is recommended to use mock data in order to simplify the component development/testing process; this likely means that you do not need to set the default locale for the sandboxed component. I have demonstrated how to set up a mock translate service in a sandbox below.

```
import { sandboxOf } from 'angular-playground';
import { of, Observable } from 'rxjs';
import { TranslateService } from '@ngx-translate/core';
import { DemoComponent } from './demo.component';

// create a mock service instance
class MockTranslateService {
  onTranslationChange = new Observable();
  onLangChange = new Observable();
  onDefaultLangChange = new Observable();
  get = () => of('foo');
}

export default sandboxOf(DemoComponent, {
    // provide the mock service instance so it can be used by Angular's dependency injection
    providers: [{ provide: TranslateService, useClass: MockTranslateService }]
})
.add('Demo', {
    template: `<div>translation is: <strong>{{ 'TITLE' | translate }}</strong></div>`
});
```
The whole sample repo can be found here: https://github.com/timstoddard/sandbox-ngx-translate

**Comment by kurpav** [comment]
I've developed my own solution:
```
export const playgroundTranslateProvider = {
  provide: APP_INITIALIZER,
  useFactory: (translate: TranslateService) => {
    return () => translate.setDefaultLang('en');
  },
  multi: true,
  deps: [TranslateService]
};
export default sandboxOf(LoginFormComponent, {
  imports: [ReactiveFormsModule],
  providers: [playgroundTranslateProvider]
})
```
And now I don't have to mock my translations. But anyway thanks for your response @timstoddard
