### ISSUE TITLE
Feature Request: declareComponent flag

### ISSUE THREAD

**Issue by isaacplmann** [SoCreate/angular-playground#15]
I'd like the option to pass a string instead of a component to the sandboxOf function so that it wouldn't automatically declare the component.  I have a bunch of shared ui components that depend on each other and I'd like to just import the whole SharedModule in my sandboxes.  If I do that, however, the component that I'm sandboxing is declared in the HostModule and the SharedModule, which is a no-no.

If this sounds like a good feature, I can work on a PR.

**Comment by jschwarty** [comment]
Yes, I can see where that's needed. 

We talked about this here at our team and think that a good way to handle this would be to update the `SandboxOfConfig` to have a property named `declareComponent` that would be true by default. This would allow for people to pass that in as false in the case that you describe, or just leave off in the default case. It would also allow for us to keep the strong typing of the component to sandbox, which is extremely helpful from a refactor and code navigation standpoint.

So the change to the `SandboxOfConfig` interface and an update to the `SandboxBuilder` to set that property in the `serialize` method...and then a change in the `ScenarioComponent` logic to support a check of that `sandbox.declareComponent` property before adding the `type` to the HostModule `declarations`.

If you would like to do a PR that'd be awesome! Let us know, otherwise we can work on adding that in. This is something that is definitely needed so it will make it into Playground one way or another. :)

**Comment by isaacplmann** [comment]
Working on a pr now

**Comment by jschwarty** [comment]
Published `v1.4.0` with this change.
