### ISSUE TITLE
feat: Show Scenario Config

### ISSUE THREAD

**Issue by isaacplmann** [SoCreate/angular-playground#16]
I'd like to add an html5 `<details>` element has the option to "Show Scenario Config".  When expanded, it would display a pretty-printed version of the scenario configuration - template, context, styles, etc.  This would be helpful for people using `angular-playground` to get code samples.

If you like the idea, I can submit a PR.

**Comment by isaacplmann** [comment]
We could potentially hide this behavior behind a flag somewhere, if you don't want it to be the default behavior.

**Comment by jschwarty** [comment]
Sorry I haven't got back to you on this yet. I need to make some time to digest this one. Will try and do that this evening. :)

**Comment by isaacplmann** [comment]
Here are some pictures, so you can see what I'm talking about:

Collapsed:
![screen shot 2017-03-02 at 9 36 00 am](https://cloud.githubusercontent.com/assets/861504/23511639/cadd7b96-ff2b-11e6-963c-49eead03e049.png)

Expanded:
![screen shot 2017-03-02 at 9 36 18 am](https://cloud.githubusercontent.com/assets/861504/23511666/ec582afa-ff2b-11e6-9c63-4d8b669ada33.png)

Breaking up the config into multiple `<details>` sections:
![screen shot 2017-03-02 at 9 34 16 am](https://cloud.githubusercontent.com/assets/861504/23511697/0b62f3da-ff2c-11e6-91c2-ab96fbf70d22.png)
![screen shot 2017-03-02 at 9 34 37 am](https://cloud.githubusercontent.com/assets/861504/23511710/12f03734-ff2c-11e6-9053-5d44f17faf82.png)


The main goal of this feature is that other developers can easily see - if I put in these inputs, the component will look like this.

**Comment by jschwarty** [comment]
What we'd like to do is keep the Playground app as lean as possible in it's default state. We explained our approach to the Playground in [this thread](https://github.com/SoCreate/angular-playground/issues/7) to try and explain how we use the tool in our workflow and to define how we want to approach it's usage and it's growth going forward.

Since then we have added the embed and deep link ability to provide a way to leverage content from Playground in a separate "documentation/discovery" type app. We have thought about potentially exposing the "sandboxOf/scenario" data (like you show in the screenshots) through a url like the embed concept.

But thinking about things a bit further based on the request you made here...we are thinking that a **plugin architecture** might be the best approach. Provide a way for people to run their own plugins within Playground. That way the base install can be the tool we need for our workflow, but can be extended to meet the needs of others who want to use it for other purposes.

I created a feature issue for more discussion on a plugin system. #19
