### ISSUE TITLE
Include additional modules though the PlaygroundModule

### ISSUE THREAD

**Issue by cgatian** [SoCreate/angular-playground#28]
@jschwarty I don't know if angular-playground should be responsible for adding the animation module.

https://github.com/SoCreate/angular-playground/blob/4aecc19543ed1bafb4a1a9190e7fb8b13207294f/src/cli/build.ts#L12

It would be convenient if the PlaygroundModule could accept an array of modules it would import for each scenario.  Currently, I create a shared/common module and then import this in every test scenario.  

```
export default sandboxOf(LoginComponent, {
  imports: [
    SharedModule
  ],
  providers: [],
  declareComponent: false
})
  .add('Login', {
    template: '<app-login></app-login>',
  })
```

I'm bringing this up because I recently updated to @angular/Material-beta.3 and they require the animations module.  I thought it was a little magically this module was being imported by the `sandboxes.ts`.

**Comment by jschwarty** [comment]
I agree, I'm not a fan of it...but to use the animations module you have to import it in your entry module (or where ever you have `BrowserModule` because it imports `BrowserModule` (and not `CommonModule`). So you can't import it at the sandbox level because Playground is already importing `BrowserModule`.

Providing a way to add to the `PlaygroundModule` is something I was thinking through but would probably require some configuration and convention and it felt a little heavy for solving this `Animation` module story. Most module dependency scenarios can be handled at the `sandboxOf` level.

But that being said, I'm totally open to coming up with a **non-magical** way to get the animations module in at that top level. 😎

**Comment by jschwarty** [comment]
This will get taken care of when #32 gets done. Closing this and referencing it in there.
