### ISSUE TITLE
check visual regression fails

### ISSUE THREAD

**Issue by bendehghan** [SoCreate/angular-playground#301]
Running angular-playground 9.0.0

### Versions

```
Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.0
@angular-devkit/build-angular   13.2.0
@angular-devkit/core            13.2.0
@angular-devkit/schematics      13.2.0
@schematics/angular             13.2.0
rxjs                            7.5.2
typescript                      4.5.5
    
```

### Repro steps
```
npx angular-playground --config angular-playground.json --check-visual-regressions
```

### Observed Behavior
```
Successfully compiled sandbox files.
Cannot read properties of undefined (reading '_launcher')
```

### Desired Behavior
```
no errors
```

**Comment by bendehghan** [comment]
Any updates on this?
Thanks...

**Comment by JustinCouto** [comment]
Sorry for the delayed response.  This feature is sort of experimental.  We built it in as sort of a proof of concept to see how it might work.  We have talked about removing it entirely because we don't have the time or resources to really make it great.  We decided to leave it in as long as it continues to work or if there were community members that would like to take on the development and maintenance of it.  If it is not currently working, we'd be happy to take a pull request if you want to put some effort into it.  If not, we will likely remove it.  Hopefully you can help make it great!

**Comment by bendehghan** [comment]
I made a pull request for this. It's a small change in the puppeteer code. 
https://github.com/SoCreate/angular-playground/pull/305

Can you please review and merge it?
Thanks :)

**Comment by JustinCouto** [comment]
Thanks for the contribution.  We will get it merged in tomorrow morning PST.
