### ISSUE TITLE
Add support for more NgModule metadata props in SandboxOfConfig

### ISSUE THREAD

**Issue by jschwarty** [SoCreate/angular-playground#33]
Add entryComponents and schemas.

**Comment by jedrichards** [comment]
I'd really dig being able to define `entryComponents` in a sandbox (to sandbox modals made with `@angular/cdk` Overlay). For some reason when I add the needed `entryComponents` and `declarations` in the root `playground.module.ts` file instead in borks my actual main app build (I get component declared in multiple module errors). Why my main build is even looking in `playground.module.ts` I'm not sure, since no app code references or imports that file.

I'm pretty new to Angular >= 2, but will there be much work involved in adding `entryComponents` support to sandboxes? Could possibly take a look ...

**Comment by FDIM** [comment]
I've made a PR that most likely fixes this issue - I'll verify if it does at work and update tomorrow.

**Comment by cdeturche** [comment]
Needed to check behavior with modals.

Thank you.
