### ISSUE TITLE
Add explanation to readme about the distinction between playground and storybook

### ISSUE THREAD

**Issue by kovalforpublic** [SoCreate/angular-playground#333]
Thank you for your work. I have a project where I'm going to integrate a solution like that, I've watched an introduction youtube video from ng-conf and I haven't seen any arguments for using this library instead of storybook.   

### Observed Behavior
 I had to find [this 2017 issue](https://github.com/SoCreate/angular-playground/issues/43) to understand the idea behind playground in the context of angular storybook (the idea AFAIK is being lightweight in comparison to storybook). It took me sometime to look for the information over the internet in order to make an informed decision. 

### Desired Behavior
 Being able to make an informed decision whether to use this one library or angular storybook in short period of time (maybe to extend readme or modify library description).

**Comment by JustinCouto** [comment]
Hi @kovalforpublic 

Thanks for reaching out.  Playground is a tool we use everyday.  It enables our frontend teams to build component even before certain parts of the apps or the backend is ready. It has a lot of overlap with storybook, but is not as full featured.  Lots of people choose playground due to it native angular feel and simplicity.  If you don't need all the features of Storybook, Angular Playground might be a good choice for you.  I wish you the best.
