### ISSUE TITLE
Missing Discoverability

### ISSUE THREAD

**Issue by ThomasDeutsch** [SoCreate/angular-playground#7]
First, thanks for your work on angular-playground. I was looking for a DEVCARDS solution in angular2-land.

As far as i can tell, there is no solution for some basic needs:
- i can not easily discover what compoments i have sandboxed.
- i can not easily view the same sandboxed component in its different states.

To solve this, i would like to create a component that can host multiple sandboxed components - how can i do that?

**Comment by jschwarty** [comment]
Hey @ThomasDeutsch! Thanks for the props. :)

**First, some back story...**

When we developed Playground we thought long and hard about the UI (or lack thereof) and usability. We needed a tool that allowed us to work a single component in isolation, staged to put it in a specific state. This tool would help us as we work on building out a component and refactoring/adding to it into the future. We identified the following as our workflow:

1. Dev is tasked with adding or working on an existing component/directive/pipe.
2. They open up their editor, pull up that component.
3. They either add a new .sandbox.ts file next to it or open the existing one, and make sure they have a scenario set up for what they need for that component.
4. They serve up the Playground, use the command bar to pull up the component by name (that they have open in their editor), and start working it.

So we built Playground to make this workflow as streamlined and as fast as possible. We actually started with a UI that listed all the sandboxed components in a side bar, but as we used the tool in our workflow we realized that it was not something that got used.

Now the viewing of a component in all its states at once, that **is** something that some of our team members (our design team to be specific) felt was important to have during our first pass. Some of this, though, was due to the fact that we have a Style Guide app that we use for discovery and display of potential usage of what we call "global components" in our applications. They were used to having that functionality, to see a component in multiple states on one screen. And that works great for a tool that is intended to be used to take inventory and to identify possible usages.

But for Playground, we needed it to be a tool that aids in the development of a component/directive/pipe more than a home for discovery. As the team started using it for that purpose, they realized that seeing it in multiple states at once wasn't as important during the development process and that it was easy enough for them to pull up the command bar and arrow up/down and select a different scenario if they wanted to quickly flip and check it out.

**Okay, now that we have the back story covered...**

### Approach One

We have been thinking about the best approach to providing this functionality while keeping Playground optimized for the primary intent of it. That Style Guide app I mentioned, we are actually planning on open sourcing that as well. One of the features in that app is the ability to view components in isolation, which is essentially the same thing as Playground. With Playground finished, we have been looking into the concept of refactoring the Style Guide to be able to leverage Playground for the isolation stuff. One of the things we are considering is extending Playground to support an *"embed"* mode, to be able to deep link to a render of a sandboxed component scenario that will display with no command bar. This would allow us (or anyone) to serve those scenarios up in a discovery application. This is the solution we feel the strongest about right now.

### Approach Two

Another approach that we are considering is adding a list panel to the Playground that is off by default, but something you can enable if you want it in the UI. We would do this as a property in the `angular-playground.json` config file that users can set if they want. And we would probably make it a shortcut key toggle to bring it out, just like the command bar, so you still have the ability to view your sandboxed component in the full frame of the browser.

Along with this, we would look at adding the ability to select the Component itself from the command bar and have a new Playground component that would render all of the scenarios at once, vertically. So you could pick a scenario to view (like you can right now) and have the option to pick all scenarios for a sandboxed component at once.

*why we're a bit hesitant about approach two...*

While we feel this would provide a solid solution for the points you brought up and on first look feel like a minimal addition, we want to be hyper-concerned about performance of the tool. We want the dev experience to be fast and amazing. One of the things that comes into play with the Playground is the fact that the app can't be AoT'd because it needs to use the compiler to dynamically render components. And the workflow is one in which you make changes to your component and you get a live reload of the tool. When this happens, the Angular bootstrap call runs again. And when the Angular code is not AoT'd, the bootstrap call gets real slow real quick as your app starts to get more and more components and bits that need to be processed during bootstrap. So we want to always make sure that the reload experience stays as fast as possible for a dev.

Now, maybe some changes in Angular will come down the pipe and we will be able to dynamically load without the compiler and we could get to AoT'ing the Playground. In that case, this concern could go away. Or, maybe the addition of two more components (side panel and multi-scenario display) is not that big of a hit at all and it is worth adding. We certainly don't want to write those off. Just things that are on our mind as we look at additions to the Playground.

### So, now what?

I am actually in the process right now of identifying how we can make our Style Guide integrate with Playground. Let me feel out that process some more, and I will also get some feedback from our team on the concepts of Approach Two and try and come up with a plan of attack in the next day or two and will let you know!

**Comment by ThomasDeutsch** [comment]
I agree, i would suggest that approach one ist a good solution, too.

There is a solution that Playground needs to beat:
- creating a html page
- add component to page

And that is basically, what Playground does. 
If you want to have your component on a single page, you do not need to create a new html file.

For approach two, you will get on a very slippery slope, simply because it is impossible to predict how the developer/designer wants to display his components.
Maybe he wants to write a a bit of text for each component, or to embedd some test results (i think this is not easily possible with karma), viewing a component in different sizes ( testing responsive design), overlay multiple components. Or not even components - I often create pages to explain a data structure, context, functions, modules, ....
It is not about components/directives/pipes as you said. It is about all aspects of an application and it is not even only about the development/design. Maybe for some it is more of a documentation, to make it easy for new developers to find examples on how to use a component.

If you want Playground more than what it is right now, my suggestion would be to try to make it easy to create awesome pages (you call it discovery application, i call it living documents).

**Comment by jschwarty** [comment]
Added deep linking and embed mode support to Playground in version `1.2.0`. Also added an example app in the repository of consuming embeds and deep linking.
<https://github.com/SoCreate/angular-playground/blob/master/CHANGELOG.md#120-2017-02-17>
