### ISSUE TITLE
Two way binding not working in sandbox

### ISSUE THREAD

**Issue by fengfranklu** [SoCreate/angular-playground#72]
Thanks for sharing this great tooling. I really like the idea and trying to get it up and running for my project. I started by experimenting on the simple angular tutorial Heros app.  Stuck on the step four two way binding. To use angular two way binding you need to import FormsModule from Angular. There is no mention in your tutorial of where to input this module. Dig into angular-playground source code, I found my-playground.module.ts and used it as the starting point, but still got the same not recognized error. There is no declared section in the my-playground.module.ts, and the AppComponent is already declared in PlaygroundCommon module, so this could be by design. Anyway, I am just trying to follow the official Angular Heros tutorial in step three and trying to get this playground working, but stuck here. If I commented out the two way binding in the hero template, it will work, but un-comment will generate errors.  Here are the code snippets:

Heroes.Component.html:
<h1>heroes works!</h1>

<div>
  <label>name:
     
  </label>
</div>

<div><span>ID: </span>{{hero.id}}</div>
<div><span>Name: </span>{{hero.name | lowercase}}</div>
<div><span>Title: </span>{{hero.title | uppercase}}</div>

my-playground.module.ts

import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { PlaygroundCommonModule } from 'angular-playground';
import { AppComponent } from 'angular-playground';
import { FormsModule } from '@angular/forms';

@NgModule({
  imports: [
    BrowserModule,
    BrowserAnimationsModule,
    PlaygroundCommonModule,
    FormsModule
  ],
  bootstrap: [AppComponent]
})
export class MyPlaygroundModule {}

main.playground.ts

import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { initializePlayground, PlaygroundModule } from 'angular-playground';
import { MyPlaygroundModule } from './my-playground.module';

initializePlayground('app-root');
platformBrowserDynamic().bootstrapModule(MyPlaygroundModule);

Any help to get pass this hurdle will be appreciated.  

Thanks. Frank

**Comment by mgmarlow** [comment]
Thanks for trying out Playground! It's hard to diagnose the issue you're having without looking at the exact error. That said, I noticed a few things about your sample code that may explain the issue.

Setting up a custom Playground module should only be used for modules that can only be imported once, the `BrowserAnimationsModule` being a perfect example of that. On the other hand, `FormsModule` can be imported multiple times at the `sandbox` level so there is no need to import at that level. Instead, it should be imported at the sandbox level.

Here's an example sandbox for this component, `heroes.component.sandbox.ts`:
```
import { sandboxOf } from 'angular-playground';
import { HeroesComponent } from './heroes.component';
import { FormsModule } from '@angular/forms';

export default sandboxOf(HeroesComponent, {
    imports: [ FormsModule ]
})
    .add('Default', {
        template: `<app-heroes></app-heroes>`
    });
```

Notice that I'm importing `FormsModule` in this sandbox because it is a dependency of this component. The ability to declare dependencies at the sandbox level is one of the main benefits of Playground: this allows you to stage components completely in isolation without needing to bundle them with the rest of your application.

Generally, you wont need to add things to your `MyPlaygroundModule` once it is initially set up.

Here's a repo with this heroes component successfully configured: https://github.com/mgmarlow/Tour-of-Heroes-Playground
