### ISSUE TITLE
feature request: add ability to open dialog with components without hotkeys

### ISSUE THREAD

**Issue by Anufriev** [SoCreate/angular-playground#74]
I need to open it on iPad. I don't know how to do it.

**Comment by JustinCouto** [comment]
Hi There, 

First of all, Thanks for your input.  You are not the first request for a UI way to access Playground's toolset and I am happy to tell you we are working on a way to make it happen.  The reason we currently don't have any UI is because we don't want our Playground App UI to interfere with your component's UI.  With that being said, we came up with a way that we think should work well and we will also provide you with the ability to remove the UI if it is in your way.  We hope to get this done in an update in the near future.

Please keep an eye on the updates we release as you are sure to see this sometime soon.

Thank you, 
Justin

**Comment by mgmarlow** [comment]
Added in #101 and #103.

When 4.0.0 gets released, you will be able to opt-in to the overlay by using the configuration system:

```typescript
// main.playground.ts
PlaygroundModule
  .configure({
    selector: 'app-root',
    overlay: true
  });

platformBrowserDynamic().bootstrapModule(PlaygroundModule);
```
